blog/urls.py
from django.conf.urls import url
from blog.views import *

app_name = 'blog'

urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),  

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    url (r'^search/$', SearchFormView.as_view(), name='search'),

    # Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name="delete",
    ),
]

bookmark/urls.py
from django.conf.urls import url
from bookmark.views import *

app_name = 'bookmark'

urlpatterns = [
    url(r'^$', BookmarkLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),

    # Example: /add/
    url(r'^add/$',
        BookmarkCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        BookmarkChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        BookmarkUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        BookmarkDeleteView.as_view(), name="delete",
    ),
]

django2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from django2.views import HomeView
from django2.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookmark/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

@python_2_unicode_compatible
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    owner = models.ForeignKey(User, null=True, on_delete=True)

    def __str__(self):
        return self.title

bookmark/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django2.views import LoginRequiredMixin

# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(BookmarkCreateView, self).form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(LoginRequiredMixin, UpdateView) :
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(LoginRequiredMixin, DeleteView) :
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Bookmark Change - {{user}}</h1>

    <table class="change-list">
        <tr>
            <th>Title</th>
            <th>Url</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
            <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Bookmark Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}Django Bookmark Detail{% endblock %}

{% block content %}
<div id="content">
    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}

{% block title %}bookmark_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h1>Bookmark Create/Update - {{user}}</h1>

    <form action="." method="post">{% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>This is a creation or update form for your bookmark.</p>

    <fieldset class="aligned">

        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>
    
        <div class="form-row">
            {{ form.url.label_tag }} {{ form.url }}
        </div>

    </fieldset>

    <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div>

    <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}Django Bookmark List{% endblock %}

{% block content %}
<div id="content">
    <h1>Bookmark List</h1>

    <ul>
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}