blog/urls.py
from django.conf.urls import url
from blog.views import *

app_name = 'blog'

urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

    # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),  

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    url (r'^search/$', SearchFormView.as_view(), name='search'),

    # Example: /add/
    url(r'^add/$',
        PostCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        PostChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        PostUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        PostDeleteView.as_view(), name="delete",
    ),
]

django2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from django2.views import HomeView
from django2.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url

from photo.views import *

app_name = 'photo'

urlpatterns = [

    # Example: /
    url(r'^$', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/99/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    # Example: /album/add/
    url(r'^album/add/$',
        AlbumPhotoCV.as_view(), name="album_add",
    ),

    # Example: /album/change/
    url(r'^album/change/$',
        AlbumChangeLV.as_view(), name="album_change",
    ),

    # Example: /album/99/update/
    url(r'^album/(?P<pk>[0-9]+)/update/$',
        AlbumPhotoUV.as_view(), name="album_update",
    ),

    # Example: /album/99/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',
        AlbumDeleteView.as_view(), name="album_delete",
    ),

    # Example: /photo/add/
    url(r'^photo/add/$',
        PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    url(r'^photo/change/$',
        PhotoChangeLV.as_view(), name="photo_change",
    ),

    # Example: /photo/99/update/
    url(r'^photo/(?P<pk>[0-9]+)/update/$',
        PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    url(r'^photo/(?P<pk>[0-9]+)/delete/$',
        PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}Django Web Programming{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

<div id="header">
    <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
    {% if user.is_active %}
    <h4 class="welcome">Welcome,
                <strong>{% firstof user.get_short_name user.get_username %}</strong> /
                <a href="{% url 'password_change' %}">Change Password</a> /
                <a href="{% url 'logout' %}">Logout</a>
    </h4>
    {% else %}
    <h4 class="welcome">Welcome, Anonymous /
                <a href="{% url 'login' %}">Login</a> /
                <a href="{% url 'register' %}">Register</a>
    </h4>
    {% endif %}
</div>

<div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
    <li><a href="{% url 'blog:index' %}">Blog</a></li>
    <li><a href="{% url 'photo:index' %}">Photo</a></li>

    <li>Add&bigtriangledown;
        <ul>
            <li><a href="{% url 'bookmark:add' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:add' %}">Post</a></li>
            <li><a href="{% url 'photo:album_add' %}">Album</a></li>
            <li><a href="{% url 'photo:photo_add' %}">Photo</a></li>
        </ul>
    </li>
    <li>Change&bigtriangledown;
        <ul>
            <li><a href="{% url 'bookmark:change' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:change' %}">Post</a></li>
            <li><a href="{% url 'photo:album_change' %}">Album</a></li>
            <li><a href="{% url 'photo:photo_change' %}">Photo</a></li>
        </ul>
    </li>

    <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
    <li><a href="{% url 'blog:search' %}">Search</a></li>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
</div>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="content_home">

    <div id="homeimg">
        <a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>

    <table id="applist">
        <tr>
        <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td class="Edit"><i><a href="#">Add</a></i></td>
        <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td class="Edit"><i><a href="#">Add</a></i></td>
        <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="#">Photo</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td class="Edit"><i><a href="#">Add</a></i></td>
        <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; shkim 2016
</div>
{% endblock footer %}